export enum Permissions {
  CLIENT_READ_PROFILE = "client.read.profile",
  CLIENT_UPDATE_PROFILE = "client.update.profile",
  CLIENT_DELETE_PROFILE = "client.delete.profile",
  CLIENT_READ_BOOKINGS = "client.read.bookings",
  CLIENT_CREATE_BOOKING = "client.create.booking",
  CLIENT_UPDATE_BOOKING = "client.update.booking",
  CLIENT_CANCEL_BOOKING = "client.cancel.booking",

  HOST_READ_PROFILE = "host.read.profile",
  HOST_UPDATE_PROFILE = "host.update.profile",
  HOST_DELETE_PROFILE = "host.delete.profile",
  HOST_READ_BOOKINGS = "host.read.bookings",
  HOST_CREATE_BOOKING = "host.create.booking",
  HOST_UPDATE_BOOKING = "host.update.booking",
  HOST_CANCEL_BOOKING = "host.cancel.booking",

  ADMIN_READ_CLIENT = "admin.read.client",
  ADMIN_CREATE_CLIENT = "admin.create.client",
  ADMIN_UPDATE_CLIENT = "admin.update.client",
  ADMIN_DELETE_CLIENT = "admin.delete.client",
  ADMIN_READ_HOST = "admin.read.host",
  ADMIN_CREATE_HOST = "admin.create.host",
  ADMIN_UPDATE_HOST = "admin.update.host",
  ADMIN_DELETE_HOST = "admin.delete.host",

  ADMIN_READ_BOOKING = "admin.read.booking",
  ADMIN_CREATE_BOOKING = "admin.create.booking",
  ADMIN_UPDATE_BOOKING = "admin.update.booking",
  ADMIN_DELETE_BOOKING = "admin.delete.booking",
}
